### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by termit-uanic** [jceb/docbook-bootstrap#4]
I have error when compile even clear template docbook. Markdown as well has error, but I need for one docbook.
Help me please.

OS: Ubuntu 16.04

Full log following below 

```
$ LANG=C make
ant -buildfile /tmp/docbook-bootstrap/build.xml -Dinput.dir="/tmp/docbook-bootstrap/scout" -Dfile="/tmp/docbook-bootstrap/scout/scout.xml" -Dfo.stylesheet="/tmp/docbook-bootstrap/scout/docbook.xsl" -Ddbootstrap.dir="/tmp/docbook-bootstrap" -Dfile.format="docbook" -Dfile.suffix=".xml" -Doutput.dir="/tmp/docbook-bootstrap/scout/build" -Doutput.rootid=  default
Buildfile: /tmp/docbook-bootstrap/build.xml

default:

output:

todocbook:

convert_docbook5:

validate:

fo:

convert:
     [xslt] Processing /tmp/docbook-bootstrap/scout/scout.xml to /tmp/docbook-bootstrap/scout/build/scout.fo
     [xslt] Loading stylesheet /tmp/docbook-bootstrap/scout/docbook.xsl
     [xslt] /tmp/docbook-bootstrap/lib/docbook-xsl/fo/math.xsl:65:38: Warning! A variable with no following sibling instructions has no effect
     [xslt] /tmp/docbook-bootstrap/lib/docbook-xsl/fo/param.xsl:199:19: Fatal Error! Namespace prefix 'exsl' has not been declared
     [xslt] Failed to process /tmp/docbook-bootstrap/scout/scout.xml

BUILD FAILED
/tmp/docbook-bootstrap/build.xml:70: The following error occurred while executing this line:
/tmp/docbook-bootstrap/build.xml:234: The following error occurred while executing this line:
/tmp/docbook-bootstrap/build.xml:347: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
       at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:157)
       at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:302)
       at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:319)
       at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:180)
       at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:878)
       at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:416)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
       at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
       at net.sf.antcontrib.logic.IfTask$ElseIf.execute(IfTask.java:144)
       at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:211)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.Target.execute(Target.java:435)
       at org.apache.tools.ant.Target.performTasks(Target.java:456)
       at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
       at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
       at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
       at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
       at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.Target.execute(Target.java:435)
       at org.apache.tools.ant.Target.performTasks(Target.java:456)
       at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
       at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
       at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
       at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
       at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.Target.execute(Target.java:435)
       at org.apache.tools.ant.Target.performTasks(Target.java:456)
       at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
       at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
       at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
       at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
       at org.apache.tools.ant.Main.runBuild(Main.java:853)
       at org.apache.tools.ant.Main.startAnt(Main.java:235)
       at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
       at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
       at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:816)
       at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:154)
       ... 77 more
Caused by: net.sf.saxon.trans.XPathException: Errors were reported during stylesheet compilation
       at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:262)
       at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:101)
       at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:813)
       ... 78 more
---------
net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
       at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:816)
       at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:154)
       at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:302)
       at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:319)
       at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:180)
       at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:878)
       at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:416)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
       at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
       at net.sf.antcontrib.logic.IfTask$ElseIf.execute(IfTask.java:144)
       at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:211)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.Target.execute(Target.java:435)
       at org.apache.tools.ant.Target.performTasks(Target.java:456)
       at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
       at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
       at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
       at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
       at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.Target.execute(Target.java:435)
       at org.apache.tools.ant.Target.performTasks(Target.java:456)
       at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
       at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
       at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
       at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
       at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at org.apache.tools.ant.Task.perform(Task.java:348)
       at org.apache.tools.ant.Target.execute(Target.java:435)
       at org.apache.tools.ant.Target.performTasks(Target.java:456)
       at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
       at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
       at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
       at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
       at org.apache.tools.ant.Main.runBuild(Main.java:853)
       at org.apache.tools.ant.Main.startAnt(Main.java:235)
       at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
       at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: net.sf.saxon.trans.XPathException: Errors were reported during stylesheet compilation
       at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:262)
       at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:101)
       at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:813)
       ... 78 more

Total time: 3 seconds
Makefile:88: recipe for target 'default' failed
make: *** [default] Error 1

```

**Comment by jceb** [comment]
Thanks for reporting the issue.  It's actually a problem in docbook-xsl.
This line reveals the issue:
`[xslt] /tmp/docbook-bootstrap/lib/docbook-xsl/fo/param.xsl:199:19: Fatal Error! Namespace prefix 'exsl' has not been declared`

In order to fix the issue, change the second line in `param.xsl` to:
`<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:exsl="http://exslt.org/common" version="1.0">`

This part has to be added:
`xmlns:exsl="http://exslt.org/common"`
